(print! (list/map (lambda (x) (+ x 1)) (list 1 2 3 4 5)))
(print! (eval! '(cons 1 2)))
(defun! say-hi ()
  (princ! "hello computer"))
(say-hi)
(setq! counter 42)
(let ((counter 0))
  (print! counter)
  (fset! 'count (lambda () (setq! counter (+ counter 1))))
  (fset! 'query (lambda () counter)))
(print! (count)) (print! (query))
(print! (count)) (print! (query))
(defun! bar (x & xs)
  (print! x)
  (print! xs))
(bar 1 2 3 4 5)
(defun! baz (& kwargs)
  (print! kwargs)
  (let ((foo (plist/get :foo kwargs))
         (bar (plist/get :bar kwargs)))
    bar))
(print! (baz :foo 10 :bar 5 :baz 3))
