(defun! foo (x)
  (+ x 1))
(print! (foo 1))
(print! (funcall 'foo 1))
(print! (list/map 'foo '(1 2 3)))
(print! (list/foldl '+ 0 '(1 2 3)))
(print! (list/take 2 '(1 2 3)))
(print! (list/take 0 '(1 2 3)))
(print! (list/take 100 '(1 2 3)))
(print! (list/drop 2 '(1 2 3)))
(print! (list/drop 10 '(1 2 3)))
(print! (list/filter 'integer? '(1 foo 2 bar baz 3 quux)))
